--- 
abstract: Single-threaded multi-tasking Catalyst engine (deprecated in favor of HTTP::Prefork)
author: Andy Grundman, <andy@hybridized.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Engine-HTTP-POE
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 0
  POE: 0
tests: t/0*.t
version: 0.08
