--- #YAML:1.0
name: Catalyst-Engine-HTTP-POE
version: 0.05
author:
  - Andy Grundman, <andy@hybridized.org>
abstract: Single-threaded multi-tasking Catalyst engine
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
